In [737]:
import pandas as pd
import numpy as np
import json
import os
import urllib3
import csv
import logging
import re
import uuid
import shortuuid
from pathlib import Path
from idmc_utils import generate_taskflow, package_import
from urllib.parse import quote

# Set the pandas options
pd.set_option('display.max_columns', None)

# Initialise the job

In [738]:
# Initialise the log file
logging.basicConfig(
    filename='logs/console.log',
    level=logging.DEBUG,
    format='%(asctime)s:%(levelname)s:%(message)s',
)

In [739]:
# Read the config file
logging.info('Reading the config file')
with open('config/config.json', 'r') as infile:
    config = json.load(infile)

# Read the Inputs

In [740]:
# Read the execution plans
logging.info('Reading the execution plans')
dfPlans = pd.read_csv('in/plans.csv', dtype='str', encoding='utf-8', na_filter=False)
dfPlans['plan_step_order'] = dfPlans['plan_step_order'].astype(int)

#TODO remove the below filter once done with testing
test_plans = [
    'Echo Employee Snapshot Oracle R12.1.3', 
    'Echo GL Balance Refresh', 
    'Echo Account Dimension', 
    'Human Resources - Oracle R1213 - Flexfield', 
    'Common-LoadDayDimension Universal',
    'Process_Quality_OracleR1213'
    #'Financials_Universal'
    ]
dfPlans = dfPlans[dfPlans['plan_name'].isin(test_plans)]

In [741]:
# Read the parameter values file
dfParamVals = pd.read_csv('in/param_values.csv', dtype='str', encoding='utf-8', na_filter=False)
dfParamVals['sequence'] = dfParamVals['sequence'].astype(float)
dfParamVals = dfParamVals.sort_values(['obj_wid', 'sequence'])

# String join the multi line values
dfParamVals = dfParamVals.groupby(['obj_wid','obj_type'])
dfParamVals = dfParamVals['textfield'].apply(lambda x: ''.join(x))
dfParamVals = pd.DataFrame(dfParamVals)
dfParamVals = dfParamVals.reset_index()
dfParamVals['param_values'] = dfParamVals['textfield'].str.split('_dac_sep_')
dfParamVals = dfParamVals.explode('param_values')
dfParamVals['value_type'] = dfParamVals['param_values'].str.extract(r'^(\S+)=')
dfParamVals['value'] = dfParamVals['param_values'].str.extract(r'^\S+=(.*)$')
dfParamVals = dfParamVals[~dfParamVals['value_type'].isna()]
dfParamVals = dfParamVals.reset_index(drop=True)
dfParamVals = dfParamVals.pivot(index=['obj_wid', 'obj_type', 'textfield'], columns=['value_type'], values=['value'])
dfParamVals = dfParamVals.reset_index()
dfParamVals.columns = ['_'.join(col).strip() for col in dfParamVals.columns.values]
dfParamVals['is_static'] = dfParamVals['value_Runtime'].apply(lambda x: False if x == 'true' else True)
dfParamVals = dfParamVals.rename(columns={'obj_wid_': 'param_wid', 'obj_type_': 'param_type', 'textfield_': 'raw_text'})

In [742]:
# Read the task and src system parameter files
dfTaskSrcParams = pd.read_csv('in/params-task-src-sys.csv', dtype='str', encoding='utf-8', na_filter=False)
dfTaskSrcParams = dfTaskSrcParams.merge(dfPlans, how='inner', on=['step_wid'])
dfTaskSrcParams = dfTaskSrcParams[['name', 'value', 'type_cd', 'step_wid', 'datatype', 'context_type', 'inactive_flag', 'comments', 'plan_name', 'step_name', 'param_wid']]
dfTaskSrcParams = dfTaskSrcParams.drop_duplicates()
#dfTaskSrcParams['param_filename'] = dfTaskSrcParams['plan_name'].apply(lambda x: re.sub(r'\W+', '_', x) + '.param')

# Join the values onto the params
dfTaskSrcParams = dfTaskSrcParams.merge(dfParamVals, how='left', on='param_wid')

In [743]:
# Read the execution parameter files
dfExecParams = pd.read_csv('in/params-exec.csv', dtype='str', encoding='utf-8', na_filter=False)
dfExecParams = dfExecParams.merge(dfPlans, how='left', on='plan_wid')
dfExecParams = dfExecParams[['param_wid', 'name', 'type_cd', 'plan_wid', 'datatype', 'context_type',
       'inactive_flag', 'comments', 'plan_name']]
dfExecParams = dfExecParams.drop_duplicates()
#dfExecParams['param_filename'] = dfExecParams['plan_name'].apply(lambda x: re.sub(r'\W+', '_', x) + '.param')
dfExecParams['name'] = dfExecParams['name'].apply(lambda x: x if x.startswith('$$') else '$$' + x if len(x) > 0 else x)

# Join the values onto the params
dfExecParams = dfExecParams.merge(dfParamVals, how='left', on='param_wid')

# Lookup the Converted Mapping Task IDs

In [744]:
# Login to IDMC
logging.info('Logging into IDMC')
http = urllib3.PoolManager()

data = '{ "username": "' + config['idmc']['user'] + '", "password": "' + config['idmc']['password'] + '" }'

url = 'https://' + config['idmc']['host'] + '/saas/public/core/v3/login'
r = http.request(
    'POST', 
    url,
    timeout=3000,
    body=data,
    headers={
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        }
    )
    
# Convert the response into a datframe
try:
    result = json.loads(r.data.decode('utf-8'))
    sessionID = result['userInfo']['sessionId']
except Exception as e:
    print(e)
    print(r.data)

In [745]:
# Get the secure agent ID
logging.info('Getting the secure agent ID')
url = 'https://' + config['idmc']['pod'] + '.' + config['idmc']['host'] + '/saas/api/v2/runtimeEnvironment/name/' + quote(config['idmc']['agentGroupName'])
r = http.request(
    'GET', 
    url,
    timeout=3000,
    headers={
            'Accept': 'application/json',
            'icSessionId': sessionID
        }
    )
    
# Convert the response into a datframe
try:
    result = json.loads(r.data.decode('utf-8'))
    agentGroupID = result['id']
    agentGroupGUID = result['federatedId']
    agentGroupName = config['idmc']['agentGroupName']
except Exception as e:
    print(e)
    print(r.data)

In [746]:
# Initialise the tasks data frame
logging.info('Getting a list of the mapping tasks')
limit = 200
i = 0
dfTasks = pd.DataFrame()

# Page through mapping task queries
while True:

    # Get a list of the mapping tasks
    url = 'https://' + config['idmc']['pod'] + '.' + config['idmc']['host'] + '/saas/public/core/v3/objects?q=type==%27MTT%27%20and%20location==%27' + config['idmc']['folderPath'] + '%27&limit=' + str(limit) + '&skip=' + str(i)
    r = http.request(
        'GET', 
        url,
        timeout=3000,
        headers={
                'Accept': 'application/json',
                'INFA-SESSION-ID': sessionID
            }
        )
        
    # Convert the response into a datframe
    result = json.loads(r.data.decode('utf-8'))
    dfTmp = pd.json_normalize(result)
    dfResp = dfTmp.copy()
    taskCount = dfResp.iloc[0]['count']
    dfResp = dfResp['objects'].explode()
    dfResp = pd.DataFrame(dfResp)
    dfResp = pd.json_normalize(dfResp['objects'])
    dfTasks = pd.concat([dfTasks, dfResp], ignore_index=True)

    # Break if all records have been returned
    i = i + limit
    if i > taskCount:
        print(f'Finished. dfCount = { len(dfTasks) }; i = { i }; taskCount = { taskCount }')
        break

    print(f'Looping. dfCount = { len(dfTasks) }; i = { i }; taskCount = { taskCount }')

# Clean up the list of returned tasks
dfTasks = dfTasks.drop(columns=['tags'])
dfTasks = dfTasks.drop_duplicates()

Looping. dfCount = 200; i = 200; taskCount = 519
Looping. dfCount = 400; i = 400; taskCount = 519
Finished. dfCount = 519; i = 600; taskCount = 519

In [747]:
# Join the IDMC info onto the plans
dfTasks['step_name'] = dfTasks['path'].apply(lambda x: os.path.basename(x))
dfTasks = dfTasks[['step_name','id','path']]
dfTasks = dfTasks.rename(columns={'id': 'infa_id', 'path': 'infa_path'})
dfPlans = dfPlans.merge(dfTasks, how='left', on='step_name')
dfPlans['agent_id'] = agentGroupID
dfPlans['agent_guid'] = agentGroupGUID
dfPlans['agent_name'] = agentGroupName
dfPlans['script_dir'] = config['local']['scriptsDir']
dfPlans['script_args'] = '' # TODO placeholder for any args that need to be passed to the step script

In [748]:
# Log an error if any plans did not find an existing matching task
dfMissing = dfPlans[(dfPlans['infa_id'] == '') | (dfPlans['infa_id'].isna())].copy()
if len(dfMissing.index) > 0:
    logging.error('Some plans are missing a converted mapping task. Please see "out/missing_tasks.csv" for more details')
    dfMissing.to_csv('out/missing_tasks.csv', index=False, quoting=csv.QUOTE_ALL)

# Generate the Parameter Files

In [749]:
dfExecParams.head()

,param_wid,name,type_cd,plan_wid,datatype,context_type,inactive_flag,comments,plan_name,param_type,raw_text,value_DB2,value_DB2-390,value_Default,value_Formatter,value_Function,value_MSSQL,value_ORACLE,value_Runtime,value_SQL,value_SourceID,value_SourceName,value_TERADATA,value_Text,value_Value,value_Variable,value_connType,value_dbType,is_static
0,1E5325F1E3F4CDC907E6DBAA45AFA5,$$TEST_JB_PARAM,Execution parameters,201C9CC7C59D167A79A2E247C6189A67,Text,Both,N,,Echo Employee Snapshot Oracle R12.1.3,defnOutboundParam.value,Text=Hello world_dac_sep_Runtime=false,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,Hello world,NaN,NaN,NaN,NaN,True

In [750]:
dfTaskSrcParams.head()

,name,value,type_cd,step_wid,datatype,context_type,inactive_flag,comments,plan_name,step_name,param_wid,param_type,raw_text,value_DB2,value_DB2-390,value_Default,value_Formatter,value_Function,value_MSSQL,value_ORACLE,value_Runtime,value_SQL,value_SourceID,value_SourceName,value_TERADATA,value_Text,value_Value,value_Variable,value_connType,value_dbType,is_static
0,$$TYPE2_FLG,,Informatica parameters,e65740f5f78d4c2d4f34fb9fb877c58,Text,Both,N,,Process_Quality_OracleR1213,SIL_CustomerLocationDimension,2B23569440EB725B39F6A7B6B09932,appParam.value,Runtime=false_dac_sep_Text=N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,True
1,$$TYPE2_FLG,,Informatica parameters,e04665658cbd57da6c4a41c852d9cfb9,Text,Both,N,,Process_Quality_OracleR1213,SIL_CustomerLocationUseDimension,EB1626F121EDFD8B65B56CF0F823C030,appParam.value,Runtime=false_dac_sep_Text=N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,True
2,$$UDATE_ALL_HISTORY,,Informatica parameters,F4D0AEF0A3BC66B7231FF8A44BBB998,Text,Both,N,,Process_Quality_OracleR1213,SIL_CustomerLocationDimension_SCDUpdate,92E924BBAB35EA7E7520AFCD68A09A,appParam.value,Runtime=false_dac_sep_Text=Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,True
3,$$UDATE_ALL_HISTORY,,Informatica parameters,ac34615f1ce66faad58f0fd62590b9,Text,Both,N,,Process_Quality_OracleR1213,SIL_InternalOrganizationDimension_SCDUpdate,3CFBEA272636FAE0FA8D6C22FB9DCBB,appParam.value,Runtime=false_dac_sep_Text=Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,True
4,$$TYPE2_FLG,,Informatica parameters,e96ff681a057aab3c83edbea7ccbef68,Text,Both,N,,Echo Account Dimension,SIL_GLAccountDimension,7DEE1E857AC6CBF5C3D1ABB91874D2C6,appParam.value,Text=N_dac_sep_Runtime=false,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,True

In [751]:
logging.info('Generating the parameter files...')

# Set the param file header
lines = ['#USE_SECTIONS', '']

# Set the taskflow level parameters
for idx, row in dfExecParams.iterrows():
    plan_name = re.sub(r'\W+', '_', row['plan_name'])
    param_name = row['name']

    lines.append(f'[Default].[{ plan_name }]')

    if row['is_static'] and row['datatype'] == 'Text':
        param_value = row['value_Text']
    elif row['is_static'] and row['datatype'] == 'Timestamp' and row['value_Function'] == 'TO_CUSTOM':
        #TODO add date conversion using the format
        param_format = row['value_Formatter']
        param_value = row['value_Value']
    elif row['datatype'] == 'SQL':
        param_value = row['value_SQL']
    else:
        param_value = row['value']
    lines.append(f"{ param_name }={ param_value }")
    lines.append('')

# Set the taskflow mapping task level parameters
for idx, row in dfTaskSrcParams.iterrows():
    plan_name = re.sub(r'\W+', '_', row['plan_name'])
    step_name = row['step_name']
    param_name = row['name']

    lines.append(f'[Default].[{ plan_name }].[{ step_name }]')

    if row['is_static'] and row['datatype'] == 'Text':
        param_value = row['value_Text']
    elif row['is_static'] and row['datatype'] == 'Timestamp' and row['value_Function'] == 'TO_CUSTOM':
        #TODO add date conversion using the format
        param_format = row['value_Formatter']
        param_value = row['value_Value']
    elif row['datatype'] == 'SQL':
        param_value = row['value_SQL']
    else:
        param_value = row['value']
    lines.append(f"{ param_name }={ param_value }")
    lines.append('')

lines.append('')

# Save the parameter file
with open(f'out/{ config['local']['paramFile'] }', 'w', encoding='utf-8') as file:
    file.write('\n'.join(lines))

# Generate the Taskflows

In [752]:
logging.info('Generating the taskflows...')

# Filter out any missing tasks
dfPlansFil = dfPlans.copy()
dfPlansFil = dfPlansFil[(dfPlansFil['infa_id'] != '') & (dfPlansFil['infa_id'].notna())]

#TODO Remove the below filter after testing is finished
#dfPlansFil = dfPlansFil[dfPlansFil['step_name']== 'SDE_Universal_APTermsDimension']

planIds = dfPlansFil['plan_wid'].unique()

for planId in planIds:

    # Get the plan for the current id
    dfPlan = dfPlansFil[dfPlansFil['plan_wid'] == planId].copy()

    # Generate the unique identifiers
    dfPlan['dac2idmc_step_id'] = dfPlan.apply(lambda x: "task" + shortuuid.uuid()[:8], axis=1)
    map_order_uuid = { step_order: "group" + shortuuid.uuid()[:8] for step_order in dfPlan['plan_step_order'].unique() }
    dfPlan = dfPlan.sort_values(['plan_wid', 'plan_step_order', 'step_name'])
    dfPlan['sequence'] = range(len(dfPlan))
    dfPlan['dac2idmc_group_id'] = dfPlan['plan_step_order'].map(map_order_uuid)
    dfPlan['dac2idmc_next_id'] = dfPlan['dac2idmc_step_id'].shift(-1)

    # Get the next group IDs and sort the plans
    dfGroups = dfPlan[['plan_step_order','dac2idmc_group_id']].copy()
    dfGroups = dfGroups.drop_duplicates()
    dfGroups = dfGroups.sort_values(['plan_step_order'])
    dfGroups['dac2idmc_next_group'] = dfGroups['dac2idmc_group_id'].shift(-1)
    dfGroups = dfGroups[['dac2idmc_group_id','dac2idmc_next_group']]

    dfPlan = dfPlan.merge(dfGroups, how='inner', on='dac2idmc_group_id')
    dfPlan = dfPlan.sort_values(['sequence'])

    #TODO Uncomment the below lines for troubleshooting
    #print(planId)
    #dfPlan.to_excel(f'out/{ planId }.xlsx')

    # Generate the taskflow ID
    taskflowID = shortuuid.uuid()
    taskflowName = dfPlan.iloc[0]['plan_name']
    taskflowName = re.sub(r'\W+', '_', taskflowName)

    logging.info(f'Create workspace tree "tmp/{ taskflowName }/Explore/Default"')

    # Create the workspace directories
    treePath = Path(f'tmp/{ taskflowName }/Explore/Default')
    treePath.mkdir(parents=True, exist_ok=True)

    logging.info(f'Generating taskflow "{ taskflowName }"')
    generate_taskflow.generate_taskflow(taskflowID, taskflowName, dfPlan, config)

    logging.info(f'Packaging taskflow "{ taskflowName }"')
    package_import.package_import(taskflowID, taskflowName, dfPlan)

    logging.info(f'Done!')

logging.info('All taskflows have been generated!')

# Testing below this line

In [753]:
dfTaskSrcParams

,name,value,type_cd,step_wid,datatype,context_type,inactive_flag,comments,plan_name,step_name,param_wid,param_type,raw_text,value_DB2,value_DB2-390,value_Default,value_Formatter,value_Function,value_MSSQL,value_ORACLE,value_Runtime,value_SQL,value_SourceID,value_SourceName,value_TERADATA,value_Text,value_Value,value_Variable,value_connType,value_dbType,is_static
0,$$TYPE2_FLG,,Informatica parameters,e65740f5f78d4c2d4f34fb9fb877c58,Text,Both,N,,Process_Quality_OracleR1213,SIL_CustomerLocationDimension,2B23569440EB725B39F6A7B6B09932,appParam.value,Runtime=false_dac_sep_Text=N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,True
1,$$TYPE2_FLG,,Informatica parameters,e04665658cbd57da6c4a41c852d9cfb9,Text,Both,N,,Process_Quality_OracleR1213,SIL_CustomerLocationUseDimension,EB1626F121EDFD8B65B56CF0F823C030,appParam.value,Runtime=false_dac_sep_Text=N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,True
2,$$UDATE_ALL_HISTORY,,Informatica parameters,F4D0AEF0A3BC66B7231FF8A44BBB998,Text,Both,N,,Process_Quality_OracleR1213,SIL_CustomerLocationDimension_SCDUpdate,92E924BBAB35EA7E7520AFCD68A09A,appParam.value,Runtime=false_dac_sep_Text=Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,True
3,$$UDATE_ALL_HISTORY,,Informatica parameters,ac34615f1ce66faad58f0fd62590b9,Text,Both,N,,Process_Quality_OracleR1213,SIL_InternalOrganizationDimension_SCDUpdate,3CFBEA272636FAE0FA8D6C22FB9DCBB,appParam.value,Runtime=false_dac_sep_Text=Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,True
4,$$TYPE2_FLG,,Informatica parameters,e96ff681a057aab3c83edbea7ccbef68,Text,Both,N,,Echo Account Dimension,SIL_GLAccountDimension,7DEE1E857AC6CBF5C3D1ABB91874D2C6,appParam.value,Text=N_dac_sep_Runtime=false,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,$$FLEX_APPLICATIONS,,Informatica parameters,C2B63851C4DAC335C7FA5B2B372B47CE,Text,Both,N,,Human Resources - Oracle R1213 - Flexfield,SDE_ORA_Flx_EBSDataTmpLoad,9B82F797D7E4655AD2A6AB80A038EFB2,appParam.value,Text=800_dac_sep_Runtime=false,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,800,NaN,NaN,NaN,NaN,True
134,$$FLEX_LANGUAGES,,Informatica parameters,5AB7AFDF5F87C38684AD107550F6907C,Text,Both,N,,Human Resources - Oracle R1213 - Flexfield,SDE_ORA_Flx_EBSSegDataTmpLoad,CF7FD9ADBDA3FDA41FEB024AFE19,appParam.value,Text='US'_dac_sep_Runtime=false,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,'US',NaN,NaN,NaN,NaN,True
135,$$LAST_REFRESH_DATE,,Informatica parameters,C1B8CAABF95A64896942EE5BDEFE5DBD,Timestamp,Both,N,,Process_Quality_OracleR1213,SDE_ORA_InternalOrganizationDimensionHierarchy...,B495DA4194B082F8846ABED21F273EF6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,$$MASTER_ORG,,Informatica parameters,2f99788587f2436dbb5ebceaa131525,Text,Both,N,Use this to define one or more Organizations. ...,Process_Quality_OracleR1213,SDE_ORA_ProductDimension,F48299FF06745F3673C58A3F5D5156A,appParam.value,Text='204'_dac_sep_Runtime=false,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,'204',NaN,NaN,NaN,NaN,True
137,$$BUDGET_NAME,,Informatica parameters,C0A5115854EE51BD2991982AEB48D214,Text,Both,N,,Echo GL Balance Refresh,TABC_PLP_CCM_Budget_Forecast_Agg_Load,E2A0983825AF94BF71D0301C519A26C8,appParam.value,"Text='TABCORP BUDGET', 'FORECAST JAN', 'FORECA...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,"'TABCORP BUDGET', 'FORECAST JAN', 'FORECAST FE...",NaN,NaN,NaN,NaN,True

In [754]:
dfExecParams

,param_wid,name,type_cd,plan_wid,datatype,context_type,inactive_flag,comments,plan_name,param_type,raw_text,value_DB2,value_DB2-390,value_Default,value_Formatter,value_Function,value_MSSQL,value_ORACLE,value_Runtime,value_SQL,value_SourceID,value_SourceName,value_TERADATA,value_Text,value_Value,value_Variable,value_connType,value_dbType,is_static
0,1E5325F1E3F4CDC907E6DBAA45AFA5,$$TEST_JB_PARAM,Execution parameters,201C9CC7C59D167A79A2E247C6189A67,Text,Both,N,,Echo Employee Snapshot Oracle R12.1.3,defnOutboundParam.value,Text=Hello world_dac_sep_Runtime=false,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,Hello world,NaN,NaN,NaN,NaN,True

In [755]:
dfPlans[dfPlans['source_system_container'] == 'DW']

Empty DataFrame
Columns: [plan_wid, plan_name, plan_inactive_flag, plan_step_wid, plan_step_order, plan_step_type, source_system_container, step_wid, step_cmd, step_name, group_name, exec_type, infa_id, infa_path, agent_id, agent_guid, agent_name, script_dir, script_args]
Index: []

In [756]:
dfPlans['source_system_container'].unique()

array(['UNIV', 'TABCORAR12.1.3', 'OracleR12.1.3'], dtype=object)